// Compt for copying as a HomePage
// This compt is used for...

import React, { Component } from 'react'
import { connect } from 'react-redux'
import Radium from 'radium'
import PropTypes from 'prop-types'
import Rx from 'rxjs'
import { withRouter } from 'react-router-dom'
import {

} from 'antd-mobile'
import Header from './Header'

class HomePage extends Component {

	render() {
		return (
			<div id='HomePage' style={comStyles().container}>
				<Header />
				<div style={comStyles().content} >
					<h1>Terms of Use</h1>
					<h2>1. Acceptance of the Terms of Use</h2>
					<p>Bytenectar, Inc. ("Bytenectar", “RentHero”, "we" or "us") operates this website and any related smartphone or mobile application (collectively, the "Website") and the RentHero online real estate concierge, offered through the Website (the "Services"). These terms of use are entered into by and between you and Bytenectar. The following terms and conditions, together with any documents they expressly incorporate by reference (collectively, the "Agreement"), govern your access to and use of the Website and the Services, whether as a guest or a registered user.
					Please read this Agreement carefully before you start to use the Website. By using the Website or the Services, or by clicking to accept or agree to this Agreement when this option is made available to you, you agree to comply with and be bound by this Agreement, our Privacy Policy, found at https://renthero.com/privacy-policy, incorporated herein by reference (the "Privacy Policy"), and such other policies and procedures as may be incorporated herein under Section 7 of this Agreement. If the individual clicking to accept or agree to this Agreement is doing so on behalf of an entity and registers such entity with this Website, then you (the individual) represent and warrant that you have authority to bind such entity and enter into this Agreement on its behalf, and all further references to "you" shall be to such entity. If you do not agree to this Agreement or the Privacy Policy, you must not access or use the Website or the Services.
					The Website and the Services are offered and available to users who are 18 years of age or older. By using the Website or the Services, you, the user, represent and warrant that you are of legal age to form a binding contract with Bytenectar and meet all of the eligibility requirements set forth herein. If you do not meet these requirements, you must not access or use the Website or the Services.
					Each of Bytenectar's service clients may be subject to one or more separate written agreements with Bytenectar or with each other (each, a "Service Agreement"). This Agreement applies only to use of the Website and the Services and in no way affects the terms and conditions of any Service Agreement.
					</p>
					<br />
					<h2>2. Changes to the Terms of Use</h2>
					<p>This version of this Agreement became effective on September 1st, 2018 and amends, restates and replaces any version effective prior to such date. We reserve the right, in our sole discretion, to modify this Agreement, in whole or in part, at any time, with or without your consent. Notification of any amendment will be posted on the Website and will be effective immediately. You are under an obligation to review the current version of this Agreement and other Bytenectar policies before using the Website or the Services. All amendments are effective immediately when we post them, and apply to all access to and use of the Website and the Services thereafter. Your use of the Website or the Services following any amendment of this Agreement will signify your assent to and acceptance of its revised terms.
					</p>
					<br />
					<h2>3. Subscription Information; Payment for Certain Services</h2>
					<p>To subscribe for certain Services and obtain access to password-protected areas of the Website, you must establish a RentHero account by providing us with current, complete and accurate information as prompted by the online enrollment form and by selecting a password, the confidentiality of which shall be your responsibility. You may not use anyone else’s RentHero account in connection with your use of the Services, or permit anyone else to use the Services or to access password-protected areas of the Website using your Bytenectar account. You agree to notify Bytenectar immediately of any actual or suspected unauthorized use of your Bytenectar account, or any other breach of security.
					Certain Services may be subject to fees charged by Bytenectar ("Fees") which will be identified at the point of purchase of such Services. Additional functionality and services may be offered or provided by us from time to time and these will be described on the Website. Services requiring Fees which have not been previously agreed upon will be notified to you, and your agreement to be responsible for any such additional Fees will be required, before any such additional Fees will be applied. We will charge your credit card for applicable authorized Fees and you understand that, once charged, such Fees are non-refundable. If Bytenectar does not receive payment from the issuer of the credit card associated with your RentHero account, you agree to pay all amounts due upon demand directly to Bytenectar, and Bytenectar further reserves the right to either suspend or terminate your RentHero account and your access to the Services in such circumstances.
					</p>
					<br />
					<h2>4. Conditions on Using the Website and the Services</h2>
					<p>The Website and the Services provide only a neutral online venue which landlords, landlord representatives, brokers, property managers, sub-lessors (collectively, "Listing Parties") and potential renters can use to find and exchange information in connection with potential transactions involving real estate and, if they choose, to arrange transactions with one another. Bytenectar does not counsel parties to real estate transactions, assess the qualifications of potential tenants to final landlords, show properties, or negotiate rental or sales contracts. Any such duties are the sole responsibility of the licensed real estate professionals dealing with tenants. No brokerage relationship or any agency or fiduciary relationship is intended to be or shall be deemed to have been created between Bytenectar and any user of the Website or Services. Additionally, real estate transactions are complicated and are governed by various laws, practices and customs. Users are advised to seek the help of a licensed real estate professional and/or a real estate attorney to help in the negotiation and completion of any real estate transaction.
					You acknowledge that if you use the Services as a potential renter of a property listed on the Website, including by participating in any offer board for, or by submitting an electronic rental application in relation to, a property listed on the Website, information that you submit through the Website (subject to the terms of the Privacy Policy) will be visible to Listing Parties associated with such property and used by them in assessing your qualifications as a tenant. If you decide to make an offer through the Services to rent any property listed on the Website, you are solely responsible for determining the rental price that you want to offer to a Listing Party for such property. All users should be sure they are comfortable with the price they are offering and be aware of the following:
					a. the acceptance of your offer by a Listing Party constitutes a binding agreement to enter into a rental agreement with such Listing Party and obligates you to pay all associated fees to Bytenectar and to such Listing Party;
					b. if participating in an offer board, placing the highest offer to a Listing Party for a property that is the subject of an offer board on the Website does not guarantee that you will get the property; and
					c. you are solely responsible for determining the reasonableness and prudence of any offer you make in light of the property and your circumstances.
					We have no control over the conduct of our users or the truth or accuracy of the information that users post on the Website. We do not endorse any persons who use or register for our Services, whether as renters or Listing Parties. We make no verification of information that any user submits to the Website. We make no representations about properties advertised on the Website, about the Listing Parties responsible for presenting such properties, about the accuracy of information provided by such Listing Parties, or about the financial capabilities of, or the accuracy of information provided by, prospective renters.
					Although we may offer features through the Services (including through third-party service providers we engage) which are intended to assist Listing Parties and potential renters to assess the appropriateness of, and to negotiate and consummate transactions among themselves, Bytenectar does not conduct any screening, background investigations or credit checks on any individual's character, creditworthiness or rental history, nor any investigations of the existence or actual state of any property listed. Any materials and information similar to qualifications are solely the self-submitted materials of the user. Bytenectar does not verify any such information for accuracy, and all parties agree to accept any such data as-is without liability on Bytenectar. All aspects of transactions between users of the Website and Services, including the existence, quality, safety or legality of the properties advertised, the truth or accuracy of listings, the ability of Listing Parties to rent a property or the ability of renters to pay for rental properties are solely the responsibility of each user and therefore users of the Website and the Services should perform all appropriate due diligence, including visiting in person any listed property, before entering into a rental contract or any other transaction with respect to such property. We strongly discourage renters from sharing sensitive confidential information directly with purported Listing Parties, or wiring funds to such parties, based solely on electronic solicitations from such parties.
					</p>
					<br />
					<h2>5. Proprietary Rights; Restrictions on Use</h2>
					<p>All software used on the Website is proprietary to us or to third parties, and except as may be required to exercise the foregoing license grant, any use, redistribution, sale, decompilation, reverse engineering, disassembly, translation or reduction of such software to human-readable form is prohibited.
					The RentHero name, the RentHero logo, and all related names, logos, product and service names, designs and slogans are registered or unregistered trademarks of RentHero or its affiliates or licensors, and may not be used in connection with any service or products other than those provided by Bytenectar, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits Bytenectar. Any use of such marks, or any others displayed on the Website, will inure solely to the benefit of their respective owners.
					The Website and Services are the property of Bytenectar. Except as expressly provided below in the case of User Data (as defined below), all the data, information, text, images (including video), designs, sound, music, marks, logos, compilations (meaning the collection, arrangement and assembly of information) and other content on or made available through the Website, and any of the foregoing sent to you by e-mail or other means (collectively, the "Site Content") are owned by Bytenectar, its licensors or other providers of such material and are protected by Canadian and United States and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.
					Bytenectar authorizes you to use the Services and access, view, use, download and print the Site Content subject to the following conditions:
					a. you may use the Services, and download, access and print the Site Content, only in reasonable limited quantities for your personal, non-commercial use;
					b. you may not modify the Site Content;
					c. any displays or print outs of the Site Content must be marked "© Bytenectar, Inc. 2011-2016. All rights reserved."; and
					d. you may not remove or alter any copyright, trademark or other proprietary rights notices that have been placed in the Site Content.
					Except as expressly permitted above, modification, reproduction, redistribution, republication, uploading, posting, transmitting, distributing or otherwise exploiting in any way the Services, the Site Content, or any portion of the Site Content, is strictly prohibited without the prior written permission of Bytenectar. If you violate any of the foregoing conditions, your right to use the Services and the Site Content will cease immediately and you must, at our option, return or destroy any copies of the materials you have made. No right, title or interest in or to the Services or the Site Content is transferred to you, and all rights not expressly granted are reserved by Bytenectar. Any use of the Services or the Site Content not expressly permitted by this Agreement is a breach of this Agreement and may violate copyright, trademark and other laws. You agree, and represent and warrant, that your use of the Services, the Website and the Site Content, or any portion thereof, will be consistent with the foregoing license, covenants and restrictions and will neither infringe nor violate the rights of any other party or breach any contract or legal duty to any other parties. In addition, you agree that you will comply with all applicable laws, regulations and ordinances relating to the Services, the Website, the Site Content or your use of them, and you will be solely responsible for your own individual violations of any of them.
					We may, in our discretion and without liability to you, with or without cause, with or without prior notice and at any time:
					a. terminate your access to our Services,
					b. deactivate or delete any of your accounts and all related information and files in such accounts and
					c. bar your access to any of such files or Services.
					</p>
					<br />
					<h2>6. Your Data</h2>
					<p>You are solely responsible for all data that you upload or transmit with us through the Website or the Services (collectively, the "User Data"). Do not transmit User Data you do not have permission to send to Bytenectar. You are responsible for creating backup copies of any User Data. By providing us with User Data you:
					a. Agree to provide only true, accurate, current and complete information about yourself and not to misrepresent your identity or your Bytenectar account information;
					b. Authorize us to make copies as we deem necessary in order to provide the Services;
					c. Give us, and you promise that you have the right to give us, an irrevocable, perpetual, non-exclusive, transferable, fully paid worldwide license to use your User Data for the purpose of delivering the Services;
					d. If you are a Listing Party using the RentHero service, give us (i) an irrevocable, perpetual (except upon termination of your use of the Services), non-exclusive, transferable, fully paid worldwide license to publish, distribute, publicly display and perform your User Data regarding apartments and other units of real property which you own or are otherwise authorized to rent or lease to third parties and to create derivative works based upon such User Data and (ii) an irrevocable, perpetual, non-exclusive, transferable, fully paid worldwide license to continue after the termination of your use of the Services to use data derived from your User Content, including from any User Content pertaining to properties that have been rented, in an aggregated form which does not identify any particular listing, for, among other things, real estate analytics, research, and creation and sale of reports containing aggregated data;
					e. Acknowledge and agree any User Data submitted through the Website will be used in accordance with the Privacy Policy, described below, and that you will not submit User Data containing any sensitive data relating to your race, color, religion, sex, handicap, familial status, or national origin; and
					f. Represent and warrant that you own all proprietary rights in your User Data or, with respect to any User Data you do not own, you have the full authority and right to transmit the User Data and to grant the licenses granted hereunder, and that the exercise by Bytenectar of the license rights granted by you shall not infringe any third party intellectual property rights, nor violate any rights of privacy or publicity, nor be defamatory, libelous or obscene, nor violate any other right, privilege or interest of any third party.
					Bytenectar is under no obligation to edit or control User Data that you transmit, and will not be in any way responsible or liable for User Data or your use of it. Subject to the rights granted to us in this Agreement, you own all of your User Data and any intellectual property rights associated with your User Data.
					Bytenectar reserves the right, in its sole discretion:
					a. to refuse to list any person, individual, Listing Party, applicant or other user;
					b. to screen any listing, and to edit the content of any listing; and
					c. to delete from any listing or edit any falsehoods, inconsistencies, offensive material or any material that infringes third party rights or that is otherwise in breach of these Terms.
					You acknowledge that Bytenectar has no obligation to do any of these things.
					Even after you remove information from your profile or delete your account, we may retain certain information to prevent identity theft and other misconduct even if deletion has been requested. Removed and deleted information may persist in backup copies indefinitely, but will not be available to others.
					</p>
					<br />
					<h2>7. Communication Transcripts</h2>
					<p>We enable users to communicate with each other and RentHero through the RentHero apps, websites, and other services. For example, we enable renters and realtors to call or text each other (in some countries, without disclosing their telephone numbers to each other). To provide this service, RentHero receives some information regarding the calls or texts, including the date and time of the call/text, and the content of the communications. RentHero may also use this information for customer support services (including to resolve disputes between users), for safety and security purposes, to improve our products and services and for analytics. In connection with your use of the Website and Services, you agree that all text and audio communications may be recorded and/or backed up for the purposes of providing the RentHero Concierge service. All such information is the property of Bytenectar Inc. and complies local government laws & regulations.
					</p>
					<br />
					<h2>8. Website Policies</h2>
					<p>In connection with your use of the Website and Services, you agree that you shall comply with any written policies and procedures for the Website and Services set forth at https://www.Bytenectar.com/terms-of-use.
					Listing Parties and Others Listing Property: You are entitled to list a property for rent ("Property") only if you own the Property, or if you are acting as the managing agent or broker for the Property, or if you have the right to sub-let a Property without violation of the head lease. You may list a Property for as long as the Property remains available for rent. You must promptly remove the Property listing from the Service if it is no longer available for rent. Bytenectar may establish limits on the maximum time that listings will remain on the Service, and Bytenectar shall have no liability or responsibility for the deletion or failure to store any listing. By listing a Property, you represent and warrant to Bytenectar that:
					a. you will provide accurate, current and complete registration and listing information;
					b. your use of the Service will comply with all applicable federal, state and local laws, regulations and rules, including without limitation the Fair Housing Act, the Fair Credit Reporting Act and any applicable rent control or rent stabilization laws, and will not violate any contract by which you are bound or any third party rights;
					c. any property that you list on the Service complies fully with all applicable health, safety and fire laws and codes;
					d. in the event you use any feature of the Services provided by a third party service provider which allows you to access a potential renter’s consumer credit data, criminal history or eviction history, you hereby certify that you have a legitimate business need for such data in connection with assessing the suitability of such potential renter as a tenant of a property listed through the Services, that your request and use of such data from such service provider shall be solely for your internal purposes in connection with a potential transaction involving such potential renter, and that you will not provide any such data to any third party; and
					f. without limitation of the foregoing, your listing will comply with the Fair Housing Act and shall not state any discriminatory preference based on race, color, national origin, religion, sex, familial status or handicap, or based on any other characteristic prohibited by state or local law.
					Renters: You are entitled to provide through the Services electronic rental applications, or offers through offer boards, if any, to Listing Parties with respect to Properties only if you meet any applicable tenant qualifications specified on the Service and you have the bona fide intention to rent the Property if it is offered to you. If your offer to a Listing Party through any such offer board is successful and your rental application, including any electronic rental application submitted through the Services, is approved by the Listing Party, you will be obligated to enter into a lease with such Listing Party and to pay in full any associated deposits to Bytenectar and/or to such Listing Party. You acknowledge and agree that you are solely responsible for the payment of any deposit required and that no negotiation is possible concerning the terms of any rental agreement applicable to a property once the offer board in connection with such property has closed.
					You understand that you may (i) submit electronic instructions through the Services to a Listing Party authorizing such Listing Party to obtain through services provided by one our third party service providers a copy of your consumer credit report and score, as well as reports of background investigations regarding your criminal and eviction history as each relates to your suitability as a tenant, or (ii) submit consent to a request from a Listing Party that it be authorized to so obtain such credit report and score or background investigation, and that in either case such submission shall constitute written instructions from you for such Listing Party to so obtain a copy of your consumer credit report and score or the results of such background investigation from such provider. By submitting the instructions or consent described in the preceding sentence, you authorize such Listing Party, once it has obtained your credit report(s) and score(s) and/or the results of such background investigations, to retain, subject to provisions of applicable law, a copy of the same in its records along with the other information you submit to such Listing Party.
					</p>
					<br />
					<h2>9. Services Restrictions</h2>
					<p>You shall not:
					a. Infringe the rights of any person or entity, including without limitation by offering to lease a property without the rights to do so;
					b. Submit, post, upload to, distribute or otherwise use, any User Data (i) in violation of, or in connection with any violation of, any local, state, national or international laws; (ii) that is libelous, defamatory, threatening, abusive, scandalous, obscene, pornographic or intended to defraud Bytenectar or any third party; (iii) that, in the sole discretion of Bytenectar, constitutes "spam"; (iv) that infringes any copyright or violates any property rights, rights of privacy or publicity, or any other rights of any third party; (v) that contains any statement, formula, direction, recipe, prescription or other matter that involves a reasonably foreseeable risk of injury, loss or damage to the material's readers or others; or (vi) that contains any software viruses or any other code, file or program that is designed to interrupt, destroy or limit the functionality of any computer software, hardware or telecommunications equipment;
					c. Impersonate any person or entity, or forge or manipulate headers to disguise the origin of any User Data;
					d. Complete transactions offline which were initiated using an offer board provided through the Website or Services;
					e. Harvest or otherwise collect any data, information or Site Content from the Website, including by using manual or automated software, devices, or other processes to "crawl", "scrape" or "spider" any page of the Website or Services to copy, obtain, propagate, distribute or misappropriate any User Data or Site Content; or
					f. Engage in any other conduct that interferes with the Website, Site Content, or Services or that restricts or inhibits any other person from using or enjoying the same, or which, in Bytenectar's sole judgment, exposes Bytenectar or any of its officers, directors, employees or agents to any liability or detriment of any type.
					</p>
					<br />
					<h2>10. Links to Third Party Websites</h2>
					<p>The Website may contain links to third-party websites or applications and our Services may include third-party content that we do not control, maintain or endorse. You expressly acknowledge and agree that we are in no way responsible or liable for any such third-party websites or applications, including, without limitation, their content, policies, failures, promotions, products, services, actions and/or any damages, losses, failures or problems caused by, related to or arising from those third parties or their sites or applications. YOUR CORRESPONDENCE AND BUSINESS DEALINGS WITH OTHERS FOUND ON OR THROUGH THE SERVICES, INCLUDING, WITHOUT LIMITATION, THE PAYMENT AND DELIVERY OF PRODUCTS AND SERVICES, AND ANY TERMS, CONDITIONS, WARRANTIES AND REPRESENTATIONS ASSOCIATED WITH ANY SUCH DEALINGS, ARE SOLELY BETWEEN YOU AND THE THIRD PARTY. Bytenectar ENCOURAGES YOU TO REVIEW ALL POLICIES, RULES, TERMS AND REGULATIONS, INCLUDING THE PRIVACY POLICIES AND TERMS OF USE OF EACH AND ANY THIRD PARTY SITE OR APPLICATION THAT YOU VISIT OR USE. Bytenectar DISCLAIMS ANY HARM THAT MAY RESULT FROM YOUR CHOICE TO USE ANY THIRD PARTY SERVICES, INCLUDING, BUT NOT LIMITED TO, THIRD PARTY SERVICES HOSTED ON THE SITE WHICH MAY ASK TO ACCESS, AND MAY RETAIN, YOUR PERSONAL INFORMATION. YOU AGREE THAT YOUR USE OF THIRD PARTY SERVICES IS AT YOUR OWN RISK.
					Listing Parties using RentHero Concierge acknowledge and agree that we provide a listing syndication service and that we will share such listings provided to us through RentHero Concierge with third parties for display on third-party websites. Such sharing does not imply endorsement of, sponsorship of, or affiliation with such third parties or their websites, and we shall not be responsible for the conduct of such third parties with respect to your listings nor any liabilities arising in connection with your listings displayed on such third party websites.
					</p>
					<br />
					<h2>11. Lead Non-Disclosure</h2>
					<p>All leads that realtors bring to RentHero will not be shared with other realtors and belongs to the original submitting party, which may be the realtor or their brokerage. Leads that already exist in the RentHero system are exempt due to their chronological pre-existence in our networks. RentHero may provide proof of such existence upon request, with sensitive details omitted. In order provide timely service and maintain the RentHero brand reputation, and leads that are not attended by realtors within a reasonable timeframe prescribed in the app interface will have its ownership transferred from the original submitting party, to RentHero’s systems and another realtor. The original submitting party will have first priority to all their submitted leads, and only a failure to service clients will trigger a lead transfer.
					</p>
					<br />
					<h2>12. Ideas Submitted to Bytenectar</h2>
					<p>In the event that you submit ideas or suggestions for the Website, Site Content or Services ("Services Comments"), the Services Comments will be deemed, and will remain, the sole property of Bytenectar. None of the Services Comments will be subject to any obligation of confidence on the part of Bytenectar, and Bytenectar will not be liable for any use or disclosure of any Services Comments. Without limiting the foregoing, Bytenectar will be entitled to unrestricted use and other exploitation of the Services Comments for any purpose whatsoever, commercial or otherwise, by any means, by any media, without compensation to the provider, author, creator or inventor of the Services Comments.
					</p>
					<br />
					<h2>13. Warranty Disclaimers, Limitation of Liability</h2>
					<p>
					a. Each party represents and warrants that: (a) it has all right, power and authority to enter into and perform this Agreement; (b) the execution of this Agreement and performance of this Agreement will not violate any other agreement to which it is a party; (c) this Agreement constitutes the legal, valid and binding obligation of such party; and (d) it shall perform this Agreement in accordance with all applicable laws. No advice or information, whether oral or written, obtained by you from Bytenectar, or through the Services, the Website or Site Content will create any warranty not expressly stated herein.
					b. If you are a paying RentHero subscriber, Bytenectar warrants that the Services will materially perform the functions described for them on the Website, provided, however, the foregoing warranty shall not apply to the extent that any problem with the Services is caused by any act or omission by you. Your sole and exclusive remedy, and Bytenectar’s sole and exclusive liability, with respect to any breach of this warranty shall be that Bytenectar shall remedy the non-conformance upon receipt of written notice from you detailing such non-conformance or if Bytenectar is unable to do so, Bytenectar will refund a portion of the Fees you paid for the nonconforming Services during the period of non-conformance.
					c. If you are not a paying Bytenectar subscriber, you use the Services, the Site Content and the Website at our own risk, and you acknowledge that you are responsible for verifying and confirming the quality, performance, accuracy and reliability of the Site Content and Services and of any data obtained by you from the Site Content or Services.
					d. EXCEPT AS SET FORTH IN THE PRECEDING CLAUSE 9.b., THE SERVICES, WEBSITE AND SITE CONTENT ARE PROVIDED IN "AS IS" CONDITION, AND Bytenectar EXPRESSLY DISCLAIMS ANY AND ALL REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING: (1) ALL WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NONINFRINGEMENT, AND ANY AND ALL WARRANTIES ARISING FROM COURSE OF DEALING AND USAGE OF TRADE; (2) THAT THE SERVICES, WEBSITE AND THE SITE CONTENT WILL MEET YOUR REQUIREMENTS, WILL ALWAYS BE AVAILABLE, ACCESSIBLE, UNINTERRUPTED, TIMELY, SECURE OR OPERATE WITHOUT ERROR; (3) AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE OPERATION, USE OR OTHER EXPLOITATION OF THE SERVICES, WEBSITE OR THE SITE CONTENT; AND (4) AS TO THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED FROM THE SERVICES, WEBSITE OR THE SITE CONTENT.
					e. No advice or information, whether oral or written, obtained by you from Bytenectar, or through the Services, the Website or Site Content will create any warranty not expressly stated herein.
					f. UNDER NO CIRCUMSTANCES WILL YOU BE ENTITLED TO RECOVER FROM BYTENECTAR ANY INCIDENTAL, CONSEQUENTIAL, INDIRECT, PUNITIVE OR SPECIAL DAMAGES (INCLUDING DAMAGES FOR LOSS OF BUSINESS, LOSS OF PROFITS OR LOSS OF USE), WHETHER BASED ON CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE ARISING FROM OR RELATING TO THE USE OF THE SERVICES, WEBSITE OR SITE CONTENT; HARM OR DAMAGE TO YOUR PERSON OR PROPERTY AS A RESULT OF USING THE SERVICES; YOUR OR ANYONE ELSE’S CONDUCT OR ACTS IN CONNECTION WITH THE USE OF THE SERVICES; OR ANY ACTUAL OR ATTEMPTED COMMUNICATION OR TRANSACTION BETWEEN USERS, IN EACH CASE, EVEN IF BYTENECTAR HAS BEEN INFORMED OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. IN THE EVENT THAT THE FOREGOING SENTENCE IS NOT ENFORCEABLE, BYTENECTAR’S MAXIMUM AGGREGATE LIABILITY TO YOU WITH RESPECT TO ANY DAMAGES ARISING IN CONNECTION WITH USE OF THE SERVICES, WEBSITE OR SITE CONTENT SHALL BE THE GREATER OF $10 OR THE AMOUNT OF ANY FEES RECEIVED BY BYTENECTAR FROM YOU DURING THE SIX-MONTH PERIOD PRIOR TO THE DATE ON WHICH THE CAUSE OF ACTION ACCRUED, WHETHER SUCH DAMAGES ARISE IN CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE. THE FOREGOING REMEDIES AND LIMITATIONS SHALL APPLY NOTWITHSTANDING THAT ANY REMEDY FAILS ITS ESSENTIAL PURPOSE. THE PROVISIONS OF THIS CLAUSE h. WERE AND ARE AN EXPRESS PART OF THE BARGAIN BETWEEN YOU AND BYTENECTAR AND WERE A CONTROLLING FACTOR IN THE SETTING OF ANY FEES PAYABLE TO BYTENECTAR.
					g. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF WARRANTIES OR OF LIABILITY, SO SOME OF THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU.
					</p>
					<br />
					<h2>14. Release; Indemnification</h2>
					<p>BY USING THE WEBSITE OR SERVICES, YOU AGREE THAT ANY LEGAL REMEDY OR LIABILITY YOU SEEK TO OBTAIN FOR ACTIONS OR OMISSIONS OF OTHER USERS WILL BE LIMITED TO A CLAIM AGAINST THE PARTICULAR USER OR USERS WHO CAUSED YOU HARM. IN THE EVENT THAT YOU HAVE A DISPUTE WITH ONE OR MORE OTHER USERS OF THE WEBSITE OR SERVICES (INCLUDING, WITHOUT LIMITATION, ANY DISPUTE BETWEEN USERS REGARDING ANY POTENTIAL OR CONSUMMATED TRANSACTION), AND IN CONSIDERATION OF OUR PROVISION OF THE SERVICES, YOU HEREBY AGREE TO RELEASE, REMISE AND FOREVER DISCHARGE BYTENECTAR AND EACH OF ITS AGENTS, DIRECTORS, OFFICERS, EMPLOYEES, AND ALL OTHER RELATED PERSONS OR ENTITIES FROM ANY AND ALL MANNER OF RIGHTS, CLAIMS, COMPLAINTS, DEMANDS, CAUSES OF ACTION, PROCEEDINGS, LIABLITIES, OBLIGATIONS, LEGAL FEES, COSTS, AND DISBURSEMENTS OF ANY NATURE WHATSOEVER, WHETHER KNOWN OR UNKNOWN, WHICH NOW OR HEREAFTER ARISE FROM, RELATE TO, OR ARE CONNECTED WITH SUCH DISPUTE AND/OR YOUR USE OF THE WEBSITE OR SERVICES. IF YOU ARE A CALIFORNIA RESIDENT, YOU WAIVE CALIFORNIA CIVIL CODE SECTION 1542, WHICH SAYS: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR."
					YOU AGREE TO INDEMNIFY AND HOLD BYTENECTAR (AND EACH OF OUR OFFICERS, DIRECTORS, AND EMPLOYEES) HARMLESS FROM ANY THIRD-PARTY CLAIM, DEMAND, ACTION, DAMAGE, LOSS, COST OR EXPENSE, INCLUDING WITHOUT LIMITATION REASONABLE ATTORNEYS’ FEES, ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICES OR ALLEGING FACTS OR CIRCUMSTANCES THAT, IF TRUE, COULD CONSTITUTE YOUR BREACH OF ANY OF THESE TERMS. WE WILL CONTROL ANY SUCH DEFENSE AND RELATED SETTLEMENT AND YOU AGREE TO REASONABLY ASSIST US THEREWITH AT YOUR EXPENSE.
					</p>
					<br />
					<h2>15. Applicable Law and Jurisdiction; Compliance</h2>
					<p>The Website and Services are operated by Bytenectar from Canada and the United States, and Bytenectar does not represent or warrant that use of the Website or Services is lawful in other jurisdictions. All matters arising from or relating to this Agreement, the Website or to the use and operation of the Services shall be governed by the substantive laws of the State of California, without regard to its conflicts of laws principles. Without derogation of the obligation to arbitrate set forth in Section 14 below, you and we agree to submit to the personal jurisdiction of the state and federal courts located in Toronto, Canada. The Uniform Computer Information Transactions Act shall not apply to this Agreement. If you gain access to the Services from locations outside Canada or the United States, you will be responsible for compliance with all local laws of any such other location, and in no event will you use the Services or Site Content in violation of U.S. export laws or regulations.
					</p>
					<br />
					<h2>16. Arbitration and Dispute Resolution.</h2>
					<p>
					All disputes arising out of or relating to this Agreement, the Website or the Services shall be resolved exclusively by binding arbitration before a single arbitrator (the "Arbitrator") in accordance with the Commercial Arbitration Rules of the American Arbitration Association (the "AAA") then in effect (for information on the AAA and its rules, see www.adr.org.) and the further procedures set forth herein, except that each party retains the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party’s copyrights, trademarks, trade secrets, patents or other intellectual property rights. The arbitration shall be conducted in Toronto, Canada, unless the Arbitrator shall determine that that venue is not reasonably convenient to all parties, in which case the Arbitrator shall determine another venue that is. In the event that the AAA is unavailable or unwilling to administer the arbitration, and the parties are unable to agree to a substitute, a substitute shall be appointed by the court. The Arbitrator shall have authority to issue any and all remedies authorized by law. The arbitration shall be governed by the Federal Arbitration Act, 9 U.S.C. §§ 2 et seq. Notwithstanding any rules of the AAA to the contrary, any claims shall be adjudicated on an individual basis only, and YOU WAIVE ANY RIGHT TO BRING ANY CLAIM AS A REPRESENTATIVE OF A PROPOSED CLASS, ON AN AGGREGATED OR MASS BASIS, OR AS A PRIVATE ATTORNEY GENERAL, OR TO CONSOLIDATE ARBITRATION PROCEEDINGS WITHOUT THE CONSENT OF ALL PARTIES THERETO. Any award rendered by the Arbitrator shall be final, conclusive and binding upon the parties hereto. In connection with any arbitration proceeding pursuant to this Agreement, unless the Arbitrator shall determine otherwise, each party shall bear its own costs and expenses. Notwithstanding the foregoing, you may at your option file an individual claim in any small claims court for disputes or claims within the scope of its subject matter jurisdiction if such court has personal jurisdiction. Bytenectar does not hereby waive any defense that such jurisdiction may be lacking in your state. Without derogation of the parties’ obligation to arbitrate as set forth herein, for any claims other than those in small claims court, jurisdiction for any court proceedings arising out of or relating to this Agreement, the Website or the Services shall be vested exclusively in, and venue shall be laid in, the state or federal courts sitting Toronto, Canada except that, following confirmation of an arbitration award in a state or federal court in Toronto, Canada, a judgment arising therefrom may be executed in any court of competent jurisdiction.
					</p>
					<br />
					<h2>17. Miscellaneous Provisions</h2>
					<p>No delay or omission by Bytenectar in exercising any of its rights occurring upon any noncompliance or default by you with respect to any of the terms and conditions of this Agreement will impair any such right or be construed to be a waiver thereof, and a waiver by Bytenectar of any of the covenants, conditions or agreements to be performed by you will not be construed to be a waiver of any succeeding breach thereof or of any other covenant, condition or agreement hereof contained. As used in this Agreement, "including" means "including but not limited to" If any provision of this Agreement is found by a court of competent jurisdiction to be invalid or unenforceable, then this Agreement will remain in full force and effect and will be reformed to be valid and enforceable while reflecting the intent of the parties to the greatest extent permitted by law. Except as otherwise expressly provided herein, this Agreement sets forth the entire agreement between you and Bytenectar regarding its subject matter, and supersedes all prior promises, agreements or representations, whether written or oral, regarding such subject matter. You shall not assign or transfer this Agreement or any right or obligation hereunder to any third party. You agree that the electronic text of this Agreement constitutes a writing and your assent to the terms and conditions hereof constitutes a "signing" for all purposes.
					</p>
					<br />
					<h2>18. Digital Millennium Copyright Act</h2>
					<p>Bytenectar complies with the provisions of the Digital Millennium Copyright Act applicable to internet service providers (17 U.S.C. §512, as amended). If you have any complaints or objections to material posted on the Website you may contact our Designated Agent at the following address:
					Bytenectar, Inc. 151 Charles St W #100, Kitchener, Ontario. Email: support@renthero.com
					Any notice alleging that materials hosted by or distributed through the Website infringe intellectual property rights must include the following information:
					a. an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other right being infringed;
					b. a description of the copyrighted work or other intellectual property that you claim has been infringed;
					c. a description of the material that you claim is infringing and where it is located on the Services;
					d. your address, telephone number, and email address;
					e. a statement by you that you have a good faith belief that the use of the materials on the Services of which you are complaining is not authorized by the copyright owner, its agent, or the law; and
					f. a statement by you that the above information in your notice is accurate and that, under penalty of perjury, you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner's behalf.
					Counter Notices
					If material that you have posted to the Website has been removed or disabled, you may file a counter notice pursuant to 17 U.S.C. §512 (g). To be effective, the counter notice must be a written communication sent to the designated agent address listed above that includes the following:
					a. a physical or electronic signature of the subscriber;
					b. identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;
					c. a statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and
					d. your name, address, and telephone number, and a statement that you consent to the jurisdiction of Federal District Court for the judicial district in which the address is located or, if your address is outside of Canada or the United States, for any judicial district in which Bytenectar may be found, and that you will accept service of process from the person who provided notification under subsection 17 U.S.C. §512 (c)(1)(C) or an agent of such person.
					</p>
				</div>

			</div>
		)
	}
}

// defines the types of variables in this.props
HomePage.propTypes = {
	history: PropTypes.object.isRequired,
}

// for all optional props, define a default value
HomePage.defaultProps = {

}

// Wrap the prop in Radium to allow JS styling
const RadiumHOC = Radium(HomePage)

// Get access to state from the Redux store
const mapReduxToProps = (redux) => {
	return {

	}
}

// Connect together the Redux store with this React component
export default withRouter(
	connect(mapReduxToProps, {

	})(RadiumHOC)
)

// ===============================

// the JS function that returns Radium JS styling
const comStyles = () => {
	return {
		container: {
      display: 'flex',
      flexDirection: 'column',
		},
		content: {
			padding: '20px',
			overflowY: 'scroll',
			fontFamily: 'Arial'
		}
	}
}
